version: '3.9'
services:
  site1:
    container_name: site1
    build:
      context: .
      dockerfile: ./Dockerfile
    image: custom
    volumes:
      - ./site:/var/www
    ports:
      - 8301:80
  site2:
    container_name: site2
    image: custom
    volumes:
      - ./site:/var/www
    ports:
      - 8302:80
  auth:
    container_name: auth
    image: custom
    volumes:
      - ./auth:/var/www
    ports:
      - 8300:80