version: '3.9'
services:
  site1:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ssoapp
    volumes:
      - ./site:/var/www
    ports:
      - 8301:80
  site2:
    image: ssoapp
    volumes:
      - ./site:/var/www
    ports:
      - 8302:80
  auth:
    image: ssoapp
    volumes:
      - ./auth:/var/www
    ports:
      - 8300:80